DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), GROUPS_ID BIGINT);
CREATE TABLE COURSE(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GROUPS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GRADE(ID BIGINT PRIMARY KEY, GRADE INT);

CREATE TABLE STUDENT_COURSE_GRADE(STUDENT_ID BIGINT, COURSE_ID BIGINT, GRADE_ID BIGINT);